### ISSUE TITLE
error.requests.includes is not a function

### ISSUE THREAD

**Issue by JandosKh** [webpack-contrib/i18n-webpack-plugin#62]
Migrated from 0.3.0 to 1.0.0. Now a lot of similar to the following errors occur:

ERROR in ./js/admin/CompanyCreationView.js
    Module parse failed: C:\MyApp\js\admin\CompanyCreationView.js error.requests.includes is not a function
    You may need an appropriate loader to handle this file type.
    TypeError: error.requests.includes is not a function
        at Parser.i18nPlugin (C:\MyApp\node_modules\i18n-webpack-plugin\dist\index.js:113:42)
        at Parser.applyPluginsBailResult1 (C:\MyApp\node_modules\tapable\lib\Tapable.js:140:27)
        at Parser.walkCallExpression (C:\MyApp\node_modules\webpack\lib\Parser.js:1102:19)
        at Parser.walkExpression (C:\MyApp\node_modules\webpack\lib\Parser.js:883:41)
        at Parser.walkExpressions (C:\MyApp\node_modules\webpack\lib\Parser.js:877:10)
        at Parser.walkCallExpression (C:\MyApp\node_modules\webpack\lib\Parser.js:1116:10)
        at Parser.walkExpression (C:\MyApp\node_modules\webpack\lib\Parser.js:883:41)
        at Parser.walkExpressions (C:\MyApp\node_modules\webpack\lib\Parser.js:877:10)
        at Parser.walkArrayExpression (C:\MyApp\node_modules\webpack\lib\Parser.js:894:9)
        at Parser.walkExpression (C:\MyApp\node_modules\webpack\lib\Parser.js:883:41)
        at Parser.walkExpressions (C:\MyApp\node_modules\webpack\lib\Parser.js:877:10)
        at Parser.walkCallExpression (C:\MyApp\node_modules\webpack\lib\Parser.js:1116:10)
        at Parser.walkExpression (C:\MyApp\node_modules\webpack\lib\Parser.js:883:41)
        at Parser.walkExpressions (C:\MyApp\node_modules\webpack\lib\Parser.js:877:10)
        at Parser.walkCallExpression (C:\MyApp\node_modules\webpack\lib\Parser.js:1116:10)
        at Parser.walkExpression (C:\MyApp\node_modules\webpack\lib\Parser.js:883:41)
        at Parser.walkExpressions (C:\MyApp\node_modules\webpack\lib\Parser.js:877:10)
        at Parser.walkArrayExpression (C:\MyApp\node_modules\webpack\lib\Parser.js:894:9)
        at Parser.walkExpression (C:\MyApp\node_modules\webpack\lib\Parser.js:883:41)
        at Parser.walkExpressions (C:\MyApp\node_modules\webpack\lib\Parser.js:877:10)
        at Parser.walkCallExpression (C:\MyApp\node_modules\webpack\lib\Parser.js:1116:10)
        at Parser.walkExpression (C:\MyApp\node_modules\webpack\lib\Parser.js:883:41)
        at Parser.walkExpressions (C:\MyApp\node_modules\webpack\lib\Parser.js:877:10)
        at Parser.walkArrayExpression (C:\MyApp\node_modules\webpack\lib\Parser.js:894:9)
        at Parser.walkExpression (C:\MyApp\node_modules\webpack\lib\Parser.js:883:41)
        at Parser.walkExpressions (C:\MyApp\node_modules\webpack\lib\Parser.js:877:10)
        at Parser.walkCallExpression (C:\MyApp\node_modules\webpack\lib\Parser.js:1116:10)
        at Parser.walkExpression (C:\MyApp\node_modules\webpack\lib\Parser.js:883:41)
        at Parser.walkExpressions (C:\MyApp\node_modules\webpack\lib\Parser.js:877:10)
        at Parser.walkArrayExpression (C:\MyApp\node_modules\webpack\lib\Parser.js:894:9)
     @ ./js/main.js 7:26-64

Webpack version is 3.5.5

**Comment by sullenor** [comment]
@JandosKh what nodejs version do you have?

**Comment by JandosKh** [comment]
"node -v" returns v4.6.0.

**Comment by JandosKh** [comment]
Well, I upgraded to node v6.11.2 LTS, and the problem went away.
